{{- if eq .Values.pilotlinkctrlr.dataservices.type "detect" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pilotlinkctrlr.pvc.detection.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.pilotlinkctrlr.pvc.detection.storage }}
  storageClassName: manual
  volumeName: {{ printf "%s-%s" .Values.namespace .Values.pilotlinkctrlr.pv.detection.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pilotlinkctrlr.pvc.hostdev.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: {{ printf "%s-%s" .Values.namespace .Values.pilotlinkctrlr.pv.hostdev.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pilotlinkctrlr.pvc.hostsys.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: {{ printf "%s-%s" .Values.namespace .Values.pilotlinkctrlr.pv.hostsys.name }}
{{- end }}